// <auto-generated />
using CompanyStructureApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyStructureApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424173016_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyStructureApi.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ceo@company.com",
                            FirstName = "Peter",
                            LastName = "Novak",
                            Phone = "0900123456",
                            Title = "CEO"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jana.hruba@company.com",
                            FirstName = "Jana",
                            LastName = "Hruba",
                            Phone = "0900765432",
                            Title = "Lead"
                        },
                        new
                        {
                            Id = 3,
                            Email = "martin.kovac@company.com",
                            FirstName = "Martin",
                            LastName = "Kovac",
                            Phone = "0911122334",
                            Title = "Lead"
                        },
                        new
                        {
                            Id = 4,
                            Email = "eva.bielikova@company.com",
                            FirstName = "Eva",
                            LastName = "Bielikova",
                            Phone = "0944556677",
                            Title = "Mgr"
                        },
                        new
                        {
                            Id = 5,
                            Email = "adam.sokol@company.com",
                            FirstName = "Adam",
                            LastName = "Sokol",
                            Phone = "0911223344",
                            Title = "Ing"
                        },
                        new
                        {
                            Id = 6,
                            Email = "lucia.kralova@company.com",
                            FirstName = "Lucia",
                            LastName = "Kralova",
                            Phone = "0909988776",
                            Title = "Bc"
                        });
                });

            modelBuilder.Entity("CompanyStructureApi.Models.OrgUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrgUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "TS",
                            ManagerId = 1,
                            Name = "Tech Solutions s.r.o.",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Code = "DEV",
                            ManagerId = 2,
                            Name = "Software Development",
                            ParentId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "OPS",
                            ManagerId = 3,
                            Name = "IT Operations",
                            ParentId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "ERP",
                            ManagerId = 4,
                            Name = "ERP System",
                            ParentId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            Code = "CLOUD",
                            ManagerId = 5,
                            Name = "Cloud Migration",
                            ParentId = 3,
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            Code = "BE",
                            ManagerId = 6,
                            Name = "Backend Team",
                            ParentId = 4,
                            Type = 3
                        },
                        new
                        {
                            Id = 7,
                            Code = "DO",
                            ManagerId = 3,
                            Name = "DevOps Team",
                            ParentId = 5,
                            Type = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
